### ISSUE TITLE
health/max health issue

### ISSUE THREAD

**Issue by snaxwell140** [codengine/SOTFEdit#18]
When modifying the max health parameter and then saving in the current save game, there seems to be an issue where it reverts back from what the user set it to (in this instance, health 50), then while back in-game, seems to revert back to the 1700-something I had it set to prior.

**Comment by Mortennif** [comment]
Can you post your savegame here, or in our discord?

**Comment by codengine** [comment]
I'll have a look, thanks for the report.

**Comment by codengine** [comment]
As @Mortennif had written, a save file would be helpful.

**Comment by codengine** [comment]
I pushed an update which will disable the Max Health box. The reason is that Max Health is calculated based on your Strength Level. So, in order to increase Max Health you would need to increase your Strength Level.

If you just want to improve your survivability, I'd suggest to wear some Armor and adjust the Durability of the Armor pieces:
![grafik](https://github.com/codengine/SOTFEdit/assets/498798/c64f4c2c-9871-4adf-9f44-cfda43eec489)

That way you are almost invincible.
